name: Build Boot app with Deployagram

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  CONTAINER_NAME: DontForget

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - uses: deployagram/deployagram-github-actions/setup@v1
        id: deployagram
        with:
          client-id: ${{ secrets.DEPLOYAGRAM_CLIENT_ID }}
          username: ${{ secrets.DEPLOYAGRAM_CLOUD_USERNAME }}
          password: ${{ secrets.DEPLOYAGRAM_CLOUD_PASSWORD }}
          license-key: ${{ secrets.DEPLOYAGRAM_LICENSE_KEY }}
          license: ${{ secrets.DEPLOYAGRAM_LICENSE }}

      - name: Build Boot App with Gradle
        id: build
        run: ./gradlew build --no-daemon --info
        env:
          DEPLOYAGRAM_LICENSE_KEY: ${{ secrets.DEPLOYAGRAM_LICENSE_KEY }}
          DEPLOYAGRAM_LICENSE: ${{ secrets.DEPLOYAGRAM_LICENSE }}

      - name: Mark test run complete
        id: mark-test-run-complete
        if: steps.build.outcome == 'success'
        uses: deployagram/deployagram-github-actions/mark-test-run-complete@v1
        with:
          container: ${{ env.CONTAINER_NAME }}
          test-run-id: gha-${{ github.run_number }}

      - name: Contract query against the collector
        id: contract-query
        if: steps.mark-test-run-complete.outcome == 'success'
        uses: deployagram/deployagram-github-actions/contract-query@v1
        with:
          container: ${{ env.CONTAINER_NAME }}
          test-run-id: gha-${{ github.run_number }}
          environment: Prod

      - name: Flush test run to cloud
        id: flush-to-cloud
        if: steps.contract-query.outcome == 'success'
        uses: deployagram/deployagram-github-actions/flush-to-cloud@v1
        with:
          container: ${{ env.CONTAINER_NAME }}

      - name: Contract check against Deployagram Cloud
        id: contract-check
        if: steps.flush-to-cloud.outcome == 'success'
        uses: deployagram/deployagram-github-actions/contract-check@v1
        with:
          token: ${{ steps.deployagram.outputs.token }}
          container: ${{ env.CONTAINER_NAME }}
          build-id: gha-${{ github.run_number }}
          environment: Prod

      # Insert step here to really deploy your app to your Prod environment

      - name: Inform Deployagram Cloud of deploy to Prod
        if: steps.contract-check.outcome == 'success'
        uses: deployagram/deployagram-github-actions/inform-deploy@v1
        with:
          token: ${{ steps.deployagram.outputs.token }}
          container: ${{ env.CONTAINER_NAME }}
          version: gha-${{ github.run_number }}
          environment: Prod
