name: Build Boot app with Deployagram

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build Boot App with Gradle
        run: ./gradlew build --no-daemon --info

      # Insert Step here to really deploy your app to your Prod environment
